# Generated by Django 4.1.1 on 2022-09-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import story.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('position', models.IntegerField(default=story.models.incrementStoryPositionbyOne)),
                ('priority', models.CharField(choices=[('FR', 'HIGHEST'), ('SO', 'CRITICAL'), ('JR', 'ALARMING'), ('SR', 'LOW')], default='SR', max_length=2)),
                ('assignee', models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='column.column')),
            ],
            options={
                'verbose_name': 'stories',
                'db_table': 'stories',
                'get_latest_by': '-created_at',
            },
        ),
    ]
