# Generated by Django 4.1.1 on 2022-09-30 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.TextField(max_length=32)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'label',
                'db_table': 'labels',
                'get_latest_by': '',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('HIGHEST', 'HIGHEST'), ('CRITICAL', 'CRITICAL'), ('ALARMING', 'ALARMING'), ('LOW', 'LOW')], default='LOW', max_length=10)),
                ('assignee', models.ManyToManyField(blank=True, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='column.column')),
                ('labels', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='story.label')),
            ],
            options={
                'verbose_name': 'story',
                'db_table': 'stories',
                'ordering': ['position'],
                'get_latest_by': '-created_at',
            },
        ),
    ]
