import Head from 'next/head'

import { useRouter } from 'next/router'
import '../styles/globals.css'
import Nav from '../components/Nav'
import { Toaster } from 'react-hot-toast'

function MyApp({ Component, pageProps }) {
   const router = useRouter()

   const hide_nav = ['/login', '/register']
   return (
      <>
         <Head>
            <title>CannBann</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <div className=' font-mono'>
            {!hide_nav.includes(router.pathname) && <Nav />}
            <Component {...pageProps} />
            <Toaster />
         </div>
      </>
   )
}

export default MyApp
