import Head from 'next/head'
import AuthorizedLayout from '../hocs/AuthorizedLayout'
import Board from '../components/Board'
import { Container } from 'postcss'
export default function Home() {
   return (
      <div>
         <Head>
            <title>CannBann</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <AuthorizedLayout>
            <main className=' mt-20'>
               <div className='  max-w-[1250px] m-auto px-14 '>
                  <Board />
               </div>
            </main>
         </AuthorizedLayout>
      </div>
   )
}
