import Head from 'next/head'
import AuthorizedLayout from '../hocs/AuthorizedLayout'

export default function Home() {
   return (
      <div>
         <Head>
            <title>Cann Bann</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <AuthorizedLayout>
            <main>lolol</main>
         </AuthorizedLayout>
      </div>
   )
}
